language: php
sudo: false
php:
- 7.1
- 7.0
before_script:
- composer install -n
addons:
  code_climate:
    repo_token: e4abd6daf008427cdcb0ff30c7c448336092f11cbd9e112bb6e7420684f3c7ff
script:
- phpunit --coverage-clover build/logs/clover.xml
after_script:
- if [ $TRAVIS_PHP_VERSION = '7.0' ]; then php vendor/bin/coveralls; fi
after_success:
- travis_retry php vendor/bin/coveralls -v
- vendor/bin/test-reporter
env:
  global:
  - secure: AQHi7aA7ay49ccSdKwMy7JdU4be50dGDgSuSopQRL45WyeLIoIUTsbGQXt4SeuWn5roIYXgm95cOtfB74hpVlslyLVugvxB6VuFJarh+qk8VOicuMGUbmorAZJElUrkepnEUnIurrVjW2rrkVjqySmRVfZ45bKvzC/rESf1YtI7BgJ+seqiSn2ZMHqHk5Hzsq8WmsWUqOsrCDrfS3iKfDjLvsdA73HtmKn9v7WYO6uIrwEzdwIbx2lHjIaOoMAGkSTDwjJuwu8lFJF+NzaF36F6WVAT4H6Mf4DpzQ7P0LzP4trJk7Q5RXxVvH5SPVd9H+YFN0eJv2Ng3xqlHjYRuuI9HqQEOw8aQsM5JG6a5DHoaycadFW15CoDPxHHU6HeQDdoPuVEAKpYKdlKR8DKZkgObEFefyPFueKyWgn9+c8Uwvg9PHQISLMqSzHz5oBHM+3rUhlNbbabu9ER7hfQjEplPG2bZCeSnzjZ6yIFqPKjuK/Jdg4vMNC3tBj5zH1S/cOBYXLwRVdjq26De60EHzrutAATu3i7FQeETQtfWM/VRt4rp179i2vAqYPQFMUT3eUEW0oUuq09QPRD+HLqjzBsmIhXcSkH+ibj5iND1UeGK/dYLz3IeXRlH1cLeConysHqiFcYbm2A4qyeOhq9UvbQtWHcrWwExQ1/4tGv+xUI=
  - secure: HOi9HlLjNBcaqGV2h33oU38fQy/2RNLdRz6VO4T5Tbz87VaPcsBS1M5hwSPRBv5kTsr9OAXUO3is8ykhI3obxvKyo1uw+P7g+osa5hkDisLvNO6xm4mPwVZhqUR2zL31RL7MzHLVMwVeL9FFAHnQe7ggvpIAUWtJbcLn1CoChYMkkzhWKRxjf1Xj85OPwsuOjXbfJYDDbnm4nlthKtVyZ1OPmxvH+HUcLBuVvJ1HkoA+H6/wd9CdVpiXW3TCpWiik78iLXDqw3bOUvtuB2K3/B87K50CQ9FWoTxyH/3BLP/M5gMXgo5RHg0JDZM2mutXc+TWheb2oaz5dtFCLzRuK+HuC0xEkBq2nSaZxodLK9fIEfusZO3+ebrp9xSvnd/FtU3b8Zd3a3QXeIHc1Dcce19ohOrYeoAegBrIIly6Yj9cvNCOeqNctGZsp0SbX068RSlrRhPifZwzf65mo45mDhf3wNzn1v+OppAR7qzQnr6L9Vyo9tTsAFAtH7LY92IDPEX2Zq/Q6ClraoU+b7AuLQwxyeVbPfGRnIcGq4H202crA4tZYfGk7nwUOVQ/C02Y7Dik1z02fLwuNQTO68qmU7Q5isI3GwvazePAHp5hqNawCJvCukVerxJ9RgtiQfxTE6/75qbfC3YV2pAxHsN9DnVR+WsXbfaUIIvsboX4lmI=
  - secure: JPbHZvrNG4KOd6zlTzrVTTblIiyw27xKOJPKjoJn+4QzcfDGc7P7/HOPgi6grkZZaYTVUZ5pWZIoRXOq+xjgx1PZbkZqtYp8TirfPWwKeJCbrhuGmlkZk74siX+806ltbD4HkXEgF1NDDc9mKBet1mdwzEeYQiiv5PS2g9kgC2W7EHIBSJZDIUMKf6+ikxyx1GYNUpTvhPUXBBnDYyTBdPI6m4ILt5adTB/SytBtN+Hbz8zPwwyUSpsGnmJxzrN3wkEZURW7/vLWDCQmBjGc+ZekemSHioHioXn5EE4/JW2moG9YJIKFpJxBl/qjqO8+6X/uU9grQ5gF/RpBgZ2sGibdjfPxeXfaDgv24vJIeV3tCw3fVoQO/rJ1awr5jn9YAz6oYigRDE8xR7wvPP2Cm10t9dP36JKRQ1QeOxtfdjiQqmyVcdAtWlr61u3tCm15Sr5yYx8aGICtAYZ94YlJuZQJm+Cjn5ZV3I4yLVglzg/8C3JBE0vLcN5Qfqh9tAjIi4ETCq8+n8al9dg3AA28Y8DLDTQkLUxMfeOgJ4m/l6IpIEnenhwS2kaFhabSIrOrGS3hqT6btFx7xnU9Xo8ztpFuOolMj0W+jntTi4ABRtwK5lWgl1AOqHpWs8Ck4gFf5GUzNlaUv9XMYreib9BHiLTbVE08N21APwismcawYPM=
