language: php
sudo: false
php:
- 7.1
- 7.0
before_script:
- composer install -n
addons:
  code_climate:
    repo_token: e4abd6daf008427cdcb0ff30c7c448336092f11cbd9e112bb6e7420684f3c7ff
script:
- phpunit --coverage-clover build/logs/clover.xml
after_script:
- if [ $TRAVIS_PHP_VERSION = '7.0' ]; then php vendor/bin/coveralls; fi
after_success:
- travis_retry php vendor/bin/coveralls -v
- vendor/bin/test-reporter
env:
  matrix:
  - secure: eP8694xeiLFCFKkdLh/A9a9QaLfkS06r3LoOHpksy8qmjl19sjzR5BsrtW/dqHdloOhQWgWXJ0owIB1U6X7SQfl6bwY7FSW6Me0a7oA5NZXqjfKeBZIboCAWIjEVJ0Jq+h7UdzQ7qXCgqlfH7SIWgTz13A8GL0LIR1tkKw3BbrAVGGjbxN2jRSpHhr8SwRq4jAwxWgKWoWydumFlaWpWv3m+P3UEdMF729iWxKz4ev9oJswcxI7lvIV9p4VlOWEDuXwHLtoKt7JfG2EJ/S1Fg8vti/17TI9Ces9nxvWQbE2Eve7ESRTPCxhtYpgzD/eSiswRTeoh6empVsLzibci94uxjGcGVo274eBPNCfuWa1qh4SQmO8LbzYUNPCHxhQLJsGrcECOirEecRvtrMMJ3dLXxk9p9C5fen0IxA1yuhdf5W1qEp4XvtlVtyRlbudJOhafc/0/Lm9Bzs6iTUX0EkRewPeXsiEs5xeKML9Rg9gbxEGnybu5YkVmjkdvlJG7fax1baHMYwYEx/tq15fh01nlm72abvpvbm3fXjwT++IjqBK3os592cZvuKjPafmtrgWWJ75cPoZQ/QB8xX2okCNcHK+mFg7W1FZ3BihhgApeYzZLDG9qeQ4bYHbK6J7WhH+uz/azU+xI0H5ZuzgBLFTr54G4/Aj/zqeOkOPphoY=
  - secure: G6RMUY/S+0LFSAVyE/1TJc933/PhnB8PHmDXGLB0tiYbrWAyDb9hgaR5YO5IkSLA8SejI99Vo7EJlJG2SVTw9tovgwXFkpZMIiiK/X5RpwlRt7h48kaUdrBtxHs+e/ur7+EDHXT2AY/ipZvr10upW24m2B3hYr8l+RkXAEjnrfnnp+RPIMfIaNURqbf7dXs7kKJfvgigocHGqJ5lmPXNmx0JZnX/Ic62nfl3XyPWCZDDoe3Vi/Mz22860Vdi4PMdA61rt6YVdWSUlWLgjNkFkQbBrHPwdiD0BV435hWTRF05Ytk9D4u/rnaSnrNT0aIYrIP5sLh37U+AHQcgxCl5x52t3CUTpafhtcmq+oR9r5v9XjzxPfNmRjEDhxmaJX1LvbDd9QkiEuVxGVu4gjYy/GPUN/Kmem+kZSE1jULmss9kqAQFxrgvmTMlIzoUuU4oL2FG0IINkO6vDc2uIK47pnUSzGFd34xxRr7Z8Zqa1JjZQJJ+PUKaAThfkF28rmZa9SRtPmzvc9u7AcQwR3DezYWCifXBhfV14gQz1BnTx1DHBkQrpIGKlomeqYtcsPfVbwD26KcgIY7KhpxtrqzgTvBYlIXEq8ck0uRiVLKsBrgApmvfaUUrf5ri484P1kaTtHichLCbqusvJL57artIPOxc7qgkmpk2/ZFaMcEDoZA=
  - secure: kt6dY2JTjSd3j5Rb/bH65CKWHY4Is5LJDv6POY7XQZsYe6PuwhwGhZbsJjeB73IwmsM47U/vH703KRoLH4pUiwGzwpajoAdDWhfT8QEAynY0/TYCU1/Ze+bn5CbLai/gClX9Zo4/s7za8AajprSbLd2pfhP/migCJqTdltBHA3kb3l8xMTLNsjsZWRymni/5mRkudtFx8Bl2aQxvP8RpcsKnXEq/iBfwryP/MuWFHc1ZTQ6MJTtsA3EkQKr1yBusr3/lhuNPwQRjRjGzDseZotqjQpyoOXymQyt3g2G+U4qWoPb/pFb8rVizWfjSEAzzAEIB8SaahulSn53QGgQOcVkj0w665mYDg4AQR1bmbdqVHcySdKz6nwCYJA5amg3E6ZjyGW9f31pbQdhbdFuM+8JNxm7wFQ56IXEK2p8v8xvawlG0ntRSpdXKw1oL791KLq7ZMt27M6/Ijx47ReF6pm4EF2osKiV4sqN7I+Sbk7B7OPkBykIJyvSBlkWjf1vr/urle/++Y5pYLEVzFfBa2gV1iJlAveR+PvpT1aenrUBkgSVM74quRPdhZQ5C5MHFweb7FX/0BCG5e+VMpe0J2l+f1wP+ufgcuH5QoncIzOOpZ3+Ita97rYJgmYeP13wiRzJjh4wDNKP+AkYiufJ/Rdk2JOAkj+MV78HCLjVAR/s=
