language: php
sudo: false
php:
- 7.1
- 7.0
before_script:
- composer install -n
addons:
  code_climate:
    repo_token: e4abd6daf008427cdcb0ff30c7c448336092f11cbd9e112bb6e7420684f3c7ff
script:
- phpunit --coverage-clover build/logs/clover.xml
after_script:
- if [ $TRAVIS_PHP_VERSION = '7.0' ]; then php vendor/bin/coveralls; fi
after_success:
- travis_retry php vendor/bin/coveralls -v
- vendor/bin/test-reporter
env:
  global:
  - secure: IvVoUoA5p+Ma3Fu8q2hSiPvP4gtO3FhsV+sU/h+pIaOMEMD3ikHYGMJfVo81mD5Bck6h2qUm2S0NVp39itk4tTXRHKjTNAOk8Vf2zWM22QzXGMlDUL5iQyEr6zkCdZoLOmeTW1JvcvPGzBk9FstIHOV6sKTi/WTJ9GhJjfNWcx4h1lQCRM05lr7Jb4cTzEdqxpDqPTSdyH/OvYGj3ZRjwrL9BMrYwj+GvpEgbLy/PKYZn492fw5a4QNwfh8JTT0fV4nDSFJtI0ORjXdRtWo5UHlCwmK4pom2X6mw8DotYfHgAFo8VRNYph8TQ2vfra8Xj9obgE3BBAcgMvvr7E+m5mrLdxdnLHGSyWTbuRRkFiG0pr23bnM8hNCVEWrKWZ+sw4+l6pl48zUKuVHIZR4jIIcHOvXpNAJUPglhtF0s3uwM1EJq9TYPMdYgEt+e5y7aiTw3kiSSJCfJFyp2lmHR1KTx1Z8SfTn+WXmtw7LGLHdi8lQVDIV+X5qyAOgeH4QFeWW8/Yex+lATTEbODURO14rf3NtTbJYkH5deTRpA5ghpjvm12/9NPK4N3b4WNhlqIhNwm5ibL+qnT5b6+h99Y6+1zga03IdFVthl/+HHinO5fMCKryw5ruwRrfxjJrzyledVXsPpoT0cN6Bc35PwTJARmVfUoE+hSqDRxZ1Fb04=
  - secure: CLkk+q68rTC+/rDQwDtEKDUn2F/+smz9UqfQfjb3dGNMehrGtbSequbChYU3P8eSQDPuUifnp+5JRzMwK9B9mDEIU68oBXmQFZPFyHEBg6lh2p7lTdy9SE8ru3D4OmNlSOqmLOy3chitgdsyciv4i174H6DnBTtE17zmUoc1/Wz32szhjsUiNVSr32yk1Jb3SeQGxT3QKAe7NPyrALwhj/Mb8kIXlk81kdGXKxfPY1vDeE7IPiSYKpa3o3jtZqx+LgFW+0CmE5TvtIsUQOQ+i4K9T5fjgm5VlXOVuHZ+5i4hqSY7KGN5Bq4DdKRvPaGYYcLmt/K/OVFZbRg0YX0oVWYGOCH0GuXXEyZjRZ3vT4LFfUOE3RHAqpxJpeP0Yed0NKzplPxOVp2GMPfsFyyy+uyjjv2CqmMA3UHOm6l7Gmf6i3U+3nCnYzGls9OCREEgQ49end92ud/EUTmYeb35xWRHHbVVQ65xIrIuLREdOrv/irAPJYrj1LPJ/xHc0llvZXyLd1zac9A8Y1iTUX4ssq756qhe6UEOL6IzAHMNXMWnHVWze387Eei7JxdokeigHLWkqbco+uuWCk50/Yae0urzLRR+SEhjOD4bQDrw8EoIj/oqX5eo494TXLLvpIYqXpB6MYvL6YW8sc6zAeLFwTjVIqbuyXm0ahlCkElhhlM=
  - secure: oEEIRCc+QB9zXHl6dx2WYqUK1pCegME4JLXCrdoMrLM+XXgy5LY9a+PyrMdENKuhbuD6PMp+fO559kw9ZaOkMRKyk2hg3mOeHj/9+9KqPfPPgYG/bZKPKBTVAWaFSzwy+IdIGJleQIXjp69+eFCmXxW5EdZqhmDUbj/TYqZBpxs0750YJW4lw4hj0czFKC85h/X3lphB12jAe8v5RON8OTPIHnwdChj07O72+XJm19Ukmdn6NWimyI1yCJvEvQpyXA5p0rj1yoD9fFjiSll+3dhjZ8ldFlUN+f2dVaOQ2KBtoE3fXtPXpRFC8tby5Wgq5ofuQ3U9DfE2iGo57p0/zSLepjpIjJ0l0eYFdyezHbr1L3WvL/dbGO5bsJ2meDnSKaPppunzg5j2GgT9AqIahRFLyUyWLIm7hcxdqHeGkjB349m7YV0D6ZIToUP2G31IGQO+CTRCI9hoNvFA9jaFw5IwlQHFKknuf45Ue6hFiwQLj989/zGGBBJV9LCkQtbW0P7f+dVxj1Zw1PecPamv94Y3q8ce3YmwQeFa0/hnyzHpU0NIQyhjAkm7cdsSNAyE/zTaQHhJ+SDRPYNdK0DZG98o9hnoU5TJ5drMf1DT+M2/nKhsGbbO94UBq3GCFCGW6p1SMd4sXdrMHDMl8M4vN+jbUWNbL9GEw88yOBwJOcw=
