language: php

sudo: false

php:
  - 7.1
  - 7.0

before_script:
  - composer install -n

addons:
  code_climate:
    repo_token: e4abd6daf008427cdcb0ff30c7c448336092f11cbd9e112bb6e7420684f3c7ff
script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - if [ $TRAVIS_PHP_VERSION = '7.0' ]; then php vendor/bin/coveralls; fi

after_success:
  - travis_retry php vendor/bin/coveralls -v
  - vendor/bin/test-reporter